services:
  wombat_monolith_service:
    image: wombat_monolith_img:latest
    container_name: wombat_monolith_container
    build: .
    pull_policy: never
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - spring.datasource.username=${POSTGRES_USER}
      - spring.datasource.password=${POSTGRES_PASSWORD}
  db:
    image: postgres:18.1
    container_name: wombat_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wombat_postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8086:8080"
    depends_on:
      - db
